[General]
image_width = 1280
image_height = 720

[RGB_Intrinsics]
fx = 0
fy = 0
cx = 0
cy = 0

[Depth_Intrinsics]
fx = 0
fy = 0
cx = 0
cy = 0

[IR_Left_Intrinsics]
fx = 0
fy = 0
cx = 0
cy = 0

[IR_Right_Intrinsics]
fx = 0
fy = 0
cx = 0
cy = 0

[IR_L2R_Rotation]
r00 = 0
r01 = 0
r02 = 0
r10 = 0
r11 = 0
r12 = 0
r20 = 0
r21 = 0
r22 = 0

[IR_L2R_Translation]
tx = 0
ty = 0
tz = 0

[IR_L2C_Rotation]
r00 = 0
r01 = 0
r02 = 0
r10 = 0
r11 = 0
r12 = 0
r20 = 0
r21 = 0
r22 = 0

[IR_L2C_Translation]
tx = 0
ty = 0
tz = 0


