[General]
image_width = 1280
image_height = 720

[RGB_Intrinsics]
fx = 0
fy = 0
cx = 0
cy = 0

[Depth_Intrinsics]
fx = 0
fy = 0
cx = 0
cy = 0

[IR_L2R_Translation]
tx = 0
ty = 0
tz = 0

[IR_L2C_Translation]
tx = 0
ty = 0
tz = 0


